### PR TITLE
Unit tests

### PR DESCRIPTION
**Pull request by olabknbit**
To run this, we have to run `swipl apps/concurrent/test/or_story.pl ` and then `?- run_tests.`. Alternative way is to run `swipl -t "load_test_files([make(all)]), run_tests." -s apps/concurrent/test/or_story.plt ` from command line.
The output is: 
```% PL-Unit: concurrent possibly executable scenario
Warning: /Users/aleksandra/Projects/ConcurrentScenario/apps/concurrent/test/or_story.pl:7:
	PL-Unit: Test run_scenario: Test succeeded with choicepoint
necessarily executable scenario
Warning: /Users/aleksandra/Projects/ConcurrentScenario/apps/concurrent/test/or_story.pl:15:
	PL-Unit: Test run_scenario: Test succeeded with choicepoint
possibly accessible gamma at t
Warning: /Users/aleksandra/Projects/ConcurrentScenario/apps/concurrent/test/or_story.pl:23:
	PL-Unit: Test run_scenario: Test succeeded with choicepoint
possibly accessible gamma at t
Warning: /Users/aleksandra/Projects/ConcurrentScenario/apps/concurrent/test/or_story.pl:31:
	PL-Unit: Test run_scenario: Test succeeded with choicepoint
necessarily accessible gamma at t
Warning: /Users/aleksandra/Projects/ConcurrentScenario/apps/concurrent/test/or_story.pl:39:
	PL-Unit: Test run_scenario: Test succeeded with choicepoint
 done
% All 5 tests passed
true.
```

**Pros**: We use swi prolog unit tests framework. It shows us warnings. We could put all the tests in one file and run it from toplevel, or figure out a command that will run all the tests in the directory.

**Cons**: You don't run them as a normal `.pl` file, eg. running `swipl apps/concurrent/test/or_story.plt ` will result in no tests being run and no info about that.

### CODE REVIEW

**Comment by olabknbit** [comment]
Let's figure out whether we should use a unit test framework for the tests. I found http://www.swi-prolog.org/pldoc/doc_for?object=section(%27packages/plunit.html%27).

**Comment by kazimierz-256** [comment]
Have you tried launching the tests from a prolog file? Can't check it myself right now but try this: `:- consult(or_story.plt), run_tests.` in a file say `all_tests.pl`

**Comment by olabknbit** [comment]
> Have you tried launching the tests from a prolog file? Can't check it myself right now but try this: `:- consult(or_story.plt), run_tests.` in a file say `all_tests.pl`

That works exactly how we want it to work! Thanks!

I think it's a nice way to run all our tests, but would like to fix the warnings before merging into `master`. Do you agree?

**Comment by olabknbit** [comment]
https://stackoverflow.com/questions/40711908/what-is-a-test-succeeded-with-choicepoint-warning-in-pl-unit-and-how-do-i-fix this is a discussion about why prolog code should be deterministic (and out isn't). @kazimierz-256  What do you feel about rewriting it so that it's deterministic? Should we do it or is it an overkill? 
I feel you have the most technical understanding of prolog concepts so you can make a decision.

**Comment by olabknbit** [comment]
@kazimierz-256  I was against merging this PR before the warnings are fixed as it makes it harder to distinguish failing tests...

**Comment by kazimierz-256** [comment]
My bad. Didn't see your polite opposition to merging with master. Please bold out that this branch is not mergeable with master in an individual comment that is still a polite notice, or assign it a label like 'dont_merge_yet'.

**Pull request merged**
