### PR TITLE
Changed nonsensible idle to *REAL* idle

### PR DESCRIPTION
**Pull request by kazimierz-256**
I have added IDLE so that the scenario is executable but there was a problem with generating an idle action (skip?). So I suggest to rotate the gangsters as a slightly more sensible than nonsensible idle action. Our tests pass

### CODE REVIEW

**Comment by brooda** [comment]
Looks good to me. @kazimierz-256, please merge.

**Review by brooda — COMMENTED** [review]
Looks good to me

**Comment by olabknbit** [comment]
Isn't an `IDLE` action an action that takes a form of `A causes true` ? I think we should have a way of detecting this type of action as Radzikowska was trying to type those actions into our program (she asked how she can do this, but we said it's not implemented). 

I have no objections with the change to the scenario, though we should accompany this change with appropriate changes to the js file with the appropriate prescribed story, I think, so that it is consistent.

**Comment by kazimierz-256** [comment]
Merged from master ability to interpret `A causes true` so that idle is a true idle and can be parsed from user input. Please note that _currently_ both action and idle action can be performed at the same time.

**Pull request merged**
